### ISSUE TITLE
tag each new release

### ISSUE THREAD

**Issue by bryan-brancotte** [scwatts/spectracl#1]
Hi,
In order to easily update ktyper deployment in Pasteur, could you tag this version, and each futur version you release ? This would allow us to specify in requirements.txt that we install `git+https://github.com/scwatts/spectracl.git@v1.0.0` and later `git+https://github.com/scwatts/spectracl.git@v1.0.1`, helping the continuous delivery to see that the dependency has changed.
Thanks for you time

**Comment by scwatts** [comment]
Hi Bryan, thank you for the suggestion. Both `ktyper` and `spectral` now have a v0.0.1 release.
